### ISSUE TITLE
Support env-variables for setting amqp host/port

### ISSUE THREAD

**Issue by chrisaq** [ChainsAutomation/chains#22]
To make starting slaves on docker easier.

Write to amqp.conf from startup-sequence file.

**Comment by olekenneth** [comment]
+1

**Comment by chrisaq** [comment]
Done.
Slaves started (in docker) with -e "AMQP=<host_ip_address>:<port_number>" will write the amqp.conf file using that variable.

e.g.:
`docker run -d --privileged --net=host -e "AMQP=192.168.0.1:5672" -v /etc/chains:/etc/chains -v /srv/chains-data:/srv/chains/data -v /dev/bus/usb:/dev/bus/usb chains/chains-slave`
